- name: Deploy hadoop
  hosts: all
  become: true
  roles:
#     - hadoop_install

- name: Config master
  hosts: all
  become: true
  roles:
     - configure

- name: Config master
  hosts: node-master
  become: true
  roles:
     - master
