- name: Deploy hadoop
  hosts: all
  roles:
#     - hadoop_install

- name: Config master
  hosts: all
  roles:
     - configure

- name: Config master
  hosts: node-master
  roles:
     - master

- name: Configure master
  hosts: node-worker 
  roles:
     - worker
