- name: Install the latest version of Java
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: latest
- name: Get stats of hadoop dir
  ansible.builtin.stat:
    path: /home/ec2-user/hadoop
  register: hd
- name: Download haddoop package
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
    dest: /home/ec2-user
  when: not hd.stat.exists
- name: Creates directory
  when: not hd.stat.exists
  file:
    path: /home/ec2-user/hadoop
    state: directory
- name: Extract hadoop to hadoop
  ansible.builtin.unarchive:
    src: /home/ec2-user/hadoop-3.3.6.tar.gz
    dest: /home/ec2-user/hadoop
  when: not hd.stat.exists
- name: update hosts file
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: |
      10.0.7.205    node-master
      10.0.7.201    node-worker
  when: not hd.stat.exists
- name: set hadoop envs
  when: not hd.stat.exists
  ansible.builtin.blockinfile:
    dest: /home/ec3-user/hadoop/etc/hadoop/hadoop-env.sh
    block: |
      export HDFS_NAMENODE_USER=ec2-user
      export HDFS_DATANODE_USER=ec2-user
      export HDFS_SECONDARYNAMENODE_USER=ec2-user
      export YARN_RESOURCEMANAGER_USER=ec2-user
      export YARN_NODEMANAGER_USER=ec2-user
      export JAVA_HOME=/usr/lib/jvm/jre-openjdk/
- name: Allow hadoop 9000tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
- name: Allow hadoop 9000udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9000/udp
    permanent: true
    state: enabled
- name: Allow hadoop 9870tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9870/tcp
    permanent: true
    state: enabled
- name: Allow hadoop 9870udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9870/udp
    permanent: true
    state: enabled
- name: Allow hadoop 8088tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8088/tcp
    permanent: true
    state: enabled
- name: Allow hadoop 8088udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8088/udp
    permanent: true
    state: enabled

