- name: Install Java 8
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.dnf:
    name: java-1.8.0-openjdk
    state: latest
- name: Install firewalld
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.dnf:
    name: firewalld
    state: latest
- name: start firewalld
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: firewalld
- name: Get stats of hadoop dir
  ansible.builtin.stat:
    path: /home/ec2-user/hadoop
  register: hd
- name: Download haddoop package
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
    dest: /home/ec2-user
  when: not hd.stat.exists
- name: Extract hadoop to hadoop
  ansible.builtin.unarchive:
    src: /home/ec2-user/hadoop-3.3.6.tar.gz
    dest: /home/ec2-user/
    extra_opts:
    - --transform
    - s/^hadoop-3.3.6/hadoop/
  when: not hd.stat.exists
- name: update hosts file
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: |
      10.0.12.12    node-master
      10.0.11.202    node-worker
  when: not hd.stat.exists
- name: set hadoop envs
  when: not hd.stat.exists
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/hadoop-env.sh
    block: |
      export HDFS_NAMENODE_USER=ec2-user
      export HDFS_DATANODE_USER=ec2-user
      export HDFS_SECONDARYNAMENODE_USER=ec2-user
      export YARN_RESOURCEMANAGER_USER=ec2-user
      export YARN_NODEMANAGER_USER=ec2-user
      export JAVA_HOME=/usr/lib/jvm/jre-openjdk/
- name: Allow hadoop 9000tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9000udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9000/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9870tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9870/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9870udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9870/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8088tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8088/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8088udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8088/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8032tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8032/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8032udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8032/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9866tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9866/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9866udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9866/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9864tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9864/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9864udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9864/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9867tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9867/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 9867udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 9867/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 80317tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8031/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8031udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8031/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 39089/tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 39089/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 39089udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 39089/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 33813/tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 33813/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 33813udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 33813/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8030/tcp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8030/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- name: Allow hadoop 8030udp
  become: true
  become_user: root
  become_method: sudo
  ansible.posix.firewalld:
    port: 8030/udp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
- ansible.posix.firewalld:
    source: 10.0.12.12
    zone: trusted
    state: enabled
    zone: public
    immediate: yes
- ansible.posix.firewalld:
    source: 10.0.11.202
    zone: trusted
    state: enabled
    zone: public
    immediate: yes 
