- name: configure name node location
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/core-site.xml
    insertafter: <configuration>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
        <property>
            <name>fs.default.name</name>
            <value>hdfs://node-master:9000</value>
        </property>
- name: configure base hdfs properties
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/hdfs-site.xml
    insertafter: <configuration>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      <property>
            <name>dfs.namenode.name.dir</name>
            <value>/home/ec2-user/hadoop/data/nameNode</value>
      </property>

      <property>
            <name>dfs.datanode.data.dir</name>
            <value>/home/ec2-user/hadoop/data/dataNode</value>
      </property>

      <property>
            <name>dfs.replication</name>
            <value>1</value>
      </property>
- name: configure yarn properties
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/mapred-site.xml
    insertafter: <configuration>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      <property>
              <name>mapreduce.framework.name</name>
              <value>yarn</value>
      </property>
      <property>
              <name>yarn.app.mapreduce.am.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
      <property>
              <name>mapreduce.map.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
      <property>
              <name>mapreduce.reduce.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
- name: configure yarn
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/yarn-site.xml
    insertafter: <configuration>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      <property>
              <name>yarn.acl.enable</name>
              <value>0</value>
      </property>
      <property>
              <name>yarn.nodemanager.aux-services</name>
              <value>mapreduce_shuffle</value>
      </property>
      <property>
              <name>yarn.nodemanager.resource.memory-mb</name>
              <value>4096</value>
      </property>
      <property>
              <name>yarn.resourcemanager.hostname</name>
              <value>node-master</value>
      </property>
- name: replace work ID with client name from /etc/hosts
  ansible.builtin.lineinfile:
    path:  /home/ec2-user/hadoop/etc/hadoop/workers
    regexp: 'localhost'
    line: node-worker
