- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: /home/ec2-user/.ssh/id_rsa
- name: Set authorized key for master
  ansible.posix.authorized_key:
    user: ec2-user
    state: present
    key: /home/ec2-user/.ssh/id_rsa.pub
