- name: configure name node location
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/core-site.xml
    insertafter: <configuration>
    block: |
        <property>
            <name>fs.default.name</name>
            <value>hdfs://node-master:9000</value>
        </property>
- name: configure base hdfs properties
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/hdfs-site.xml
    insertafter: <configuration>
    block: |
    <property>
            <name>dfs.namenode.name.dir</name>
            <value>/home/hadoop/data/nameNode</value>
    </property>

    <property>
            <name>dfs.datanode.data.dir</name>
            <value>/home/hadoop/data/dataNode</value>
    </property>

    <property>
            <name>dfs.replication</name>
            <value>1</value>
    </property>
