- name: configure name node location
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/core-site.xml
    insertafter: <configuration>
    block: |
        <property>
            <name>fs.default.name</name>
            <value>hdfs://node-master:9000</value>
        </property>
- name: configure base hdfs properties
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/hdfs-site.xml
    insertafter: <configuration>
    block: |
      <property>
            <name>dfs.namenode.name.dir</name>
            <value>/home/hadoop/data/nameNode</value>
      </property>

      <property>
            <name>dfs.datanode.data.dir</name>
            <value>/home/hadoop/data/dataNode</value>
      </property>

      <property>
            <name>dfs.replication</name>
            <value>1</value>
      </property>
- name: configure yarn properties
  ansible.builtin.blockinfile:
    dest: /home/ec2-user/hadoop/etc/hadoop/mapred-site.xml
    insertafter: <configuration>
    block: |
      <property>
              <name>mapreduce.framework.name</name>
              <value>yarn</value>
      </property>
      <property>
              <name>yarn.app.mapreduce.am.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
      <property>
              <name>mapreduce.map.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
      <property>
              <name>mapreduce.reduce.env</name>
              <value>HADOOP_MAPRED_HOME=$HADOOP_HOME</value>
      </property>
